!
!  PrismicPsi.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/5/2011 12:44:06 AM
!
module class_PrismPsi
use SharedTypes

	implicit none
	public ::  Evaluate

contains

	function make_PrismicPsiContainer(n,m) result(outPsiContainer)
		integer :: n,m
		type (PsiContainer) :: outPsiContainer

		outPsiContainer = PsiContainer(n,m,2)


	end function make_PrismicPsiContainer

	subroutine Evaluate(this,x,f,df)

		type(PsiContainer),intent(in) :: this
		real, intent(in) :: x
		real, intent(out) :: f,df
			
		integer n,m

		m=this%m
		n=this%n

		f = PsiEq(x,n,m)
		df = DiffPsiEq(x,n,m)

	end subroutine Evaluate

	function PsiEq(x,n,m) result(y)
	real :: x,y
	integer :: n,m
	real :: Pi =  3.141592653589793
		y=(n**2-m**2)*(sin(((n-m)*x-pi)/m)**2-sin(((n+m)*x-pi)/m)**2)-4*n*m*(sin(x)**2-sin((n*x-pi)/m)**2)
		  

	end function PsiEq

	function DiffPsiEq(x,n,m) result(y)
	real :: x,y
	integer :: n,m
	real :: Pi =  3.141592653589793
		y=(n**2-m**2)*(2*sin(((n-m)*x-Pi)/m)*cos(((n-m)*x-Pi)/m)*(n-m)/m-2*sin(((n+m)*x-Pi)/m)*cos(((n+m)*x-Pi)/m)*(n+m)/m)- &
		4*n*m*(2*sin(x)*cos(x)-2*sin((n*x-Pi)/m)*cos((n*x-Pi)/m)*n/m)
	end function DiffPsiEq

end module class_PrismPsi