!
!  PsiContainer.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  10/1/2011 2:25:08 PM
!
module SharedTypes

	type PsiContainer
			integer :: n,m
			integer :: PsiType
	end type PsiContainer

end module SharedTypes